---
- name: Clone Git Repository
  git:
    clone: "yes"
    accept_hostkey: "yes"
    dest: "{{item.dest | default(gitvenv_clone_dir)}}/{{item.name}}"
    repo: "{{ item.url | default(gitvenv_base_url + '/' + item.name + '.git') }}"
    track_submodules: "{{ item.tracksubmodules|default('no') }}"
    umask: "0077"
    bare: "{{item.bare|default('no')}}"
  remote_user: "{{gitvenv_user}}"
  with_items: "{{gitvenv_repositories}}"

- name: Create virtualenv with pip >= 9.0.1 in it (temporary fix until Debian Stretch is out)
  pip:
    chdir: "{{item.dest|default(gitvenv_clone_dir)}}/{{item[0].name}}"
    name: "{{item[1]}}"
    virtualenv: "{{gitvenv_workon_home_dir}}/{{item[0].name}}"
    virtualenv_python: "{{item[0].python|default(gitvenv_python)}}"
    virtualenv_site_packages: "{{item[0].site_packages|default('no')}}"
  remote_user: "{{gitvenv_user}}"
  with_nested:
    - "{{gitvenv_repositories}}"
    - ["pip>=9.0.1",  "packaging"]

- name: Requirement file to use
  debug: var="gitvenv_requirements_file"

- name: Create a virtualenv for the cloned repository and install requirements in it
  pip:
    chdir: "{{item.dest|default(gitvenv_clone_dir)}}/{{item.name}}"
    requirements: "{{item.dest|default(gitvenv_clone_dir)}}/{{item.name}}/{{item.requirements|default(gitvenv_requirements_file)}}"
    virtualenv: "{{gitvenv_workon_home_dir}}/{{item.name}}"
    virtualenv_python: "{{item.python|default(gitvenv_python)}}"
    virtualenv_site_packages: "{{item.site_packages|default('no')}}"
  remote_user: "{{gitvenv_user}}"
  with_items: "{{gitvenv_repositories}}"

- name: Install cloned code inside the virtualenv
  pip:
    chdir: "{{item.dest|default(gitvenv_clone_dir)}}/{{item.name}}"
    editable: True
    name: "{{item.dest|default(gitvenv_clone_dir)}}/{{item.name}}"
    virtualenv: "{{gitvenv_workon_home_dir}}/{{item.name}}"
  remote_user: "{{gitvenv_user}}"
  when: "{{item.install|default(false)}}"
  with_items: "{{gitvenv_repositories}}"

- name: Setup user shell to use the virtual environments
  lineinfile:
    dest: "~/.bashrc"
    line: "export WORKON_HOME='{{gitvenv_workon_home_dir}}'"
    regexp: "^export\\W*WORKON_HOME=.*"
    state: present
  remote_user: "{{gitvenv_user}}"

- name: Setup user default active virtual environment
  lineinfile:
    dest: "~/.bashrc"
    line: "workon {{item.name}}"
    regexp: "^workon\\W*"
    state: present
  remote_user: "{{gitvenv_user}}"
  when: "item.default|default(false)"
  with_items: "{{gitvenv_repositories}}"
